spring.application.name=acta-mongo-api

server.port=${PORT:8081}
spring.jackson.time-zone=America/Sao_Paulo

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/acta_db}
acta.pg-api.base-url=${ACTA_PG_API_BASE_URL:http://localhost:8080/api/v1/}
acta.pg-api.connect-timeout=${ACTA_PG_API_CONNECT_TIMEOUT:3s}
acta.pg-api.read-timeout=${ACTA_PG_API_READ_TIMEOUT:5s}