spring.application.name=acta-mongo-api

server.port=${PORT:8081}
spring.jackson.time-zone=America/Sao_Paulo
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/acta}
acta.pg-api.base-url=${ACTA_PG_API_BASE_URL:https://acta-pg-api.onrender.com}